default: &default
  adapter: postgresql
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("DB_PORT") { '5432' } %>
  username: <%= ENV.fetch("DB_USERNAME") { 'root' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'root' } %>
  sslmode: <%= ENV.fetch("DB_SSLMODE") { 'disable' } %>

development:
  <<: *default
  database: good_night_development

test:
  <<: *default
  database: good_night_test

production:
  <<: *default
  database: good_night_production
