@startuml SleepRecordList
title Sleep Record List - Sequence Diagram

' Define actors and components
actor User
participant "SleepRecordController" as Controller
participant "SleepRecordUsecase::List" as Usecase
participant "SleepRecord Repository" as SleepRecordRepository
participant "RepairSleepRecordFanoutJob" as Job
database "PostgreSQL" as DB

User -> Controller: GET /sleep_records
activate Controller

@enduml